config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/profile' => 'home#profile'

  get 'auth/:provider/callback', to: "sessions#create"

  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

  resources :polls do
    resources :options do
      member do
        post 'vote'
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'sign_in/google_oauth2' => "api#google_oauth2"
    namespace :v1 do
      resources :polls
      post 'vote' => "votes#cast_vote"
      get 'users/:id' => "users#show"
      get 'users/:id/followers' => "users#get_followers"
      get 'users/:id/follows' => "users#get_follows"
      get 'users/:id/follow' => "follows#create"
      get 'users/:id/unfollow' => "follows#destroy"
      get 'users/:user_id/polls' => "polls#user_polls"
      get 'feed' => "polls#feed"
    end
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base

	belongs_to :user
	has_many :options, dependent: :destroy
	accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true

end

app/controllers/api/v1/polls_controller.rb
class Api::V1::PollsController < Api::ApiController

	before_action :set_poll, only: [:show, :update, :destroy]
	before_action :set_user, only: [:user_polls]
	before_action :authenticate

	require 'action_view'
	require 'action_view/helpers'
	include ActionView::Helpers::DateHelper

	def index
		limit = params[:limit] ||= 1
		offset = params[:offset] ||= 0
		@polls = Poll.order('created_at DESC').limit(limit).offset(offset)
		render json: @polls, scope: {current_user: @current_user}
	end

	def show
		if @poll
			render :json => @poll
		else
			render :json => {}, :status => 404
		end
	end

	def create
		@poll = Poll.new(poll_params)
		@poll.user_id = @current_user.id

		if @poll.save
			render :show, status: :created, location: @poll
		else
			render json: @poll.errors, status: :unprocessable_entity
		end
	end

	def update
		if @current_user != @poll.user
			render :json => {"errors":{"status": "401 Unauthorized", "message": "unauthorized access"}}, :status => :unauthorized
			return false
		end

		if @poll.update(poll_params)
			render :show, status: :ok, location: @poll
		else
			render json: @poll.errors, status: :unprocessable_entity
		end
	end

	def destroy
		if @current_user == @poll.user
			@poll.destroy
			head :no_content
		else
			head :unauthorized
		end
	end

	def user_polls
    @polls = Poll.find_by(user_id: @user.id)
    render json: @polls
  end

  def feed
    ids = @current_user.follows.map(&:target_id).push(@current_user.id)
    @polls = Poll.where(user_id: ids)
    render json: @polls
  end

	private

	def set_poll
		@poll = Poll.find(params[:id])
	end

	def set_user
		@user = User.find(params[:user_id])
	end

	def poll_params
    params.require(:poll).permit(:title, options_attributes: [:id, :name, :_destroy])
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title, options_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/api/v1/polls_helper.rb
module Api::V1::PollsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.haml
= simple_form_for @poll do |f|
	= f.input :title, input_html: {  class: "form-control" }
	%h3 Options
	#options
		= f.simple_fields_for :options, @poll.options.limit(4).offset(0) do |option|
			= render 'option_fields', f: option
	.links
		= @poll.options.length
		= link_to_add_association 'add option', f, :options
	= f.submit

app/views/polls/_option_fields.html.haml
.nested-fields
	= f.input :name, input_html: { class: "form-control" }
	= link_to_remove_association "remove option", f

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

app/views/polls/index.html.haml
%h1 Listing polls
%br/
- @polls.each do |poll|
  .poll-item
    %h3= link_to poll.title, poll
    %hr/
    -poll.options.each do |option|
      .poll-item-option
        = option.name
        = option.votes.count
        = button_to "Vote", vote_poll_option_path(poll, option), method: :post, class: "btn btn-success"
    %hr/
    = link_to 'Edit', edit_poll_path(poll), class: "btn btn-info"
    = link_to 'Destroy', poll, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

%br

= link_to 'New Poll', new_poll_path

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
%p#notice= notice

%p
	%b Title:
	= @poll.title
	- @poll.options.each do |option|
		%p= option.name
		%p= option.votes.count
		= button_to 'Vote', vote_poll_option_path(@poll, option), method: :post, class: "btn btn-success"

= link_to 'Edit', edit_poll_path(@poll)
\|
= link_to 'Back', polls_path