config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/profile' => 'home#profile'

  get 'auth/:provider/callback', to: "sessions#create"

  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

  resources :polls do
    resources :options do
      member do
        post 'vote'
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'sign_in/google_oauth2' => "api#google_oauth2"
    namespace :v1 do
      resources :polls
      post 'vote' => "votes#cast_vote"
      get 'users/:id' => "users#show"
      get 'users/:id/followers' => "users#get_followers"
      get 'users/:id/follows' => "users#get_follows"
      get 'users/:id/follow' => "follows#create"
      get 'users/:id/unfollow' => "follows#destroy"
      get 'users/:user_id/polls' => "polls#user_polls"
      get 'feed' => "polls#feed"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestProject1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brand", root_path, class: "navbar-brand" %>
    </div>

      <div class="collapse navbar-collapse" id="example-navbar">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Google Login", "/auth/google_oauth2" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

	<div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-info"><%= value %></div>
    <% end %>
		<%= yield %>
	</div>

</body>
</html>